- name:  port test
  hosts: test
  gather_facts: True
  tasks:
    - name: port
      wait_for:
       host: "{{ ansible_hostname }}"
       port: 8100
       timeout: 1
    - debug: msg="System {{ ansible_hostname }} has uuid {{ ansible_product_uuid }}"
