web:
  image: nginx
  volumes:
    - /etc/nginx:/etc/nginx
  ports:
   - "80:80"
   - "443:443"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
  command: [nginx-debug, '-g', 'daemon off;']
